export const LANGUAGE = 'LANGUAGE'
export const SCREEN_RESOLUTION = 'SCREEN_RESOLUTION'
export const OPERATING_SYSTEM = 'OPERATING_SYSTEM'
export const BROWSER = 'BROWSER'
export const JAVA = 'JAVA'
export const COOKIE = 'COOKIE'
